Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Bath__c.field-meta.xml
<CustomField>
    <fullName>Bath__c</fullName>
    <label>Bath</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <label>Bed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_1__c.field-meta.xml
<CustomField>
    <fullName>Picture_1__c</fullName>
    <label>Picture 1</label>
    <type>Url</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_2__c.field-meta.xml
<CustomField>
    <fullName>Picture_2__c</fullName>
    <label>Picture 2</label>
    <type>Url</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_3__c.field-meta.xml
<CustomField>
    <fullName>Picture_3__c</fullName>
    <label>Picture 3</label>
    <type>Url</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_4__c.field-meta.xml
<CustomField>
    <fullName>Picture_4__c</fullName>
    <label>Picture 4</label>
    <type>Url</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_5__c.field-meta.xml
<CustomField>
    <fullName>Picture_5__c</fullName>
    <label>Picture 5</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Bath__c.field-meta.xml
<CustomField>
    <fullName>Bath__c</fullName>
    <label>Bath</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <label>Bed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/combo_desc__c.field-meta.xml
<CustomField>
    <fullName>combo_desc__c</fullName>
    <label>combo desc</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_1__c.field-meta.xml
<CustomField>
    <fullName>Picture_1__c</fullName>
    <label>Picture 1</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_2__c.field-meta.xml
<CustomField>
    <fullName>Picture_2__c</fullName>
    <label>Picture 2</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_3__c.field-meta.xml
<CustomField>
    <fullName>Picture_3__c</fullName>
    <label>Picture 3</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_4__c.field-meta.xml
<CustomField>
    <fullName>Picture_4__c</fullName>
    <label>Picture 4</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_5__c.field-meta.xml
<CustomField>
    <fullName>Picture_5__c</fullName>
    <label>Picture 5</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price of the Property</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Owner</label>
    <referenceTo>Property_Owner__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Realtor__c.field-meta.xml
<CustomField>
    <fullName>Realtor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realtor</label>
    <referenceTo>Realtor__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property_Owner__c/Property_Owner__c.object-meta.xml
<CustomObject>
    <label>Property Owner</label>
    <nameField>
        <label>Sellers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/objects/Realtor__c/Realtor__c.object-meta.xml
<CustomObject>
    <label>Realtor</label>
    <nameField>
        <label>Realtor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realtors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/classes/AEApexTest.cls
@isTest
public class AEApexTest {
	
    @isTest
    private static void propertyInfoSTest(){
        propertyAppHelper.getPropertyInfo();
        Property__C prop = new Property__C();
        prop.Name = 'test guy';
       	insert prop;
        propertyAppHelper.getPropertyInfo();
        List<Property__C> testList = [SELECT Id, Name, Address__c, Bath__c, Bed__c, Description__c, Location__c, Picture_1__c, Picture_2__c, Picture_4__c, Picture_3__c, Picture_5__c, Price__c, Property_Owner__c, Realtor__c,combo_desc__C FROM Property__c];
        system.assertEquals(1, testList.size());
    }
     @isTest
    private static void propertyInfoBTest(){
        propertyAppHelper.getPropertyInfo();
        List<Property__C> propList = new List<Property__C>();
        integer I;
        for(i=0;i<100;i++){
            Property__C prop = new Property__C();
            prop.name = 'test guy';
        	propList.add(prop);
        }
        insert propList;
        propertyAppHelper.getPropertyInfo();
        List<Property__C> testList = [SELECT Id, Name, Address__c, Bath__c, Bed__c, Description__c, Location__c, Picture_1__c, Picture_2__c, Picture_4__c, Picture_3__c, Picture_5__c, Price__c, Property_Owner__c, Realtor__c,combo_desc__C FROM Property__c];
        system.assertEquals(100, testList.size());
    }
    @isTest
    private static void propertyInfoNTest(){
        List<Property__C> testList = [SELECT Id, Name, Address__c, Bath__c, Bed__c, Description__c, Location__c, Picture_1__c, Picture_2__c, Picture_4__c, Picture_3__c, Picture_5__c, Price__c, Property_Owner__c, Realtor__c,combo_desc__C FROM Property__c];
        system.assertEquals(0, testList.size());
    }
     @isTest
    private static void getAllRegionsNTest(){
        propertyAppHelper.getAllRegions();
        List<Property__C> testList = [SELECT Location__c FROM Property__C];
        system.assertEquals(0, testList.size());
    }
     @isTest
    private static void getAllRegionsSTest(){
        
        Property__C prop = new Property__C();
        prop.Name = 'test guy';
       	insert prop;
        List<Property__C> testList = [SELECT Location__c FROM Property__C];
        system.assertEquals(1, testList.size());
    }
    @isTest
    private static void getAllRegionsBTest(){
        propertyAppHelper.getAllRegions();
         List<Property__C> propList = new List<Property__C>();
        integer I;
        for(i=0;i<100;i++){
            Property__C prop = new Property__C();
            prop.name = 'test guy';
        	propList.add(prop);
        }
        insert propList;
        List<Property__C> testList = [SELECT Location__c FROM Property__C];
        system.assertEquals(100, testList.size());
    }
    @isTest
    private static void createPropertySTest(){
        List<Opportunity> oList = new List<Opportunity>();
        integer I;
         for(i=0;i<1;i++){
            Opportunity o = new Opportunity();
            date datafiller = date.newInstance(2021, 1, 26);
        	o.StageName = 'Closed Won';
        	o.Name = 'test';
            o.CloseDate = datafiller;
            o.Bath__c = 2;
            o.Bed__c = 2;
             oList.add(o);
        }
        triggerHelperAE.createProperty(oList);
        List<Property__C> testList = [SELECT Location__c FROM Property__C];
        system.assertEquals(1, testList.size());
            
    }
     @isTest
    private static void createPropertyBTest(){
        List<Opportunity> oList = new List<Opportunity>();
        integer I;
         for(i=0;i<100;i++){
            Opportunity o = new Opportunity();
            date datafiller = date.newInstance(2021, 1, 26);
        	o.StageName = 'Closed Won';
        	o.Name = 'test';
            o.CloseDate = datafiller;
            o.Bath__c = 2;
            o.Bed__c = 2;
             oList.add(o);
        }
        triggerHelperAE.createProperty(oList);
        List<Property__C> testList = [SELECT Location__c FROM Property__C];
        system.assertEquals(100, testList.size());
            
    }
     @isTest
    private static void createPropertyNTest(){
        List<Opportunity> oList = new List<Opportunity>();
        integer I;
         for(i=0;i<0;i++){
            Opportunity o = new Opportunity();
            date datafiller = date.newInstance(2021, 1, 26);
        	o.StageName = 'Closed Won';
        	o.Name = 'test';
            o.CloseDate = datafiller;
            o.Bath__c = 2;
            o.Bed__c = 2;
             oList.add(o);
        }
        triggerHelperAE.createProperty(oList);
        List<Property__C> testList = [SELECT Location__c FROM Property__C];
        system.assertEquals(0, testList.size());
            
    }
     @isTest
    private static void createPropertyOwnerSTest(){
        List<Opportunity> oList = new List<Opportunity>();
        integer I;
         for(i=0;i<1;i++){
            Opportunity o = new Opportunity();
            date datafiller = date.newInstance(2021, 1, 26);
        	o.StageName = 'Closed Won';
        	o.Name = 'test';
            o.CloseDate = datafiller;
            o.Bath__c = 2;
            o.Bed__c = 2;
             oList.add(o);
        }
        insert oList;
        list<User> uList = [SELECT Id,Name From User];
        List<Opportunity> oTest = [SELECT Id,CreatedByID,StageName From Opportunity];
        triggerHelperAE.createPropertyOwner(otest);
        List<Property_Owner__c> testList = [SELECT Id,CreatedByID FROM Property_Owner__c];
        system.assertEquals(1, testlist.size());
            
    }
      @isTest
    private static void createPropertyOwnerBTest(){
        List<Opportunity> oList = new List<Opportunity>();
        integer I;
         for(i=0;i<100;i++){
            Opportunity o = new Opportunity();
            date datafiller = date.newInstance(2021, 1, 26);
        	o.StageName = 'Closed Won';
        	o.Name = 'test';
            o.CloseDate = datafiller;
            o.Bath__c = 2;
            o.Bed__c = 2;
             oList.add(o);
        }
        insert oList;
        list<User> uList = [SELECT Id,Name From User];
        List<Opportunity> oTest = [SELECT Id,CreatedByID,StageName From Opportunity];
        triggerHelperAE.createPropertyOwner(otest);
        List<Property_Owner__c> testList = [SELECT Id,CreatedByID FROM Property_Owner__c];
        system.assertEquals(100, testlist.size());
            
    }
    
}