Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Bath__c.field-meta.xml
<CustomField>
    <fullName>Bath__c</fullName>
    <label>Bath</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <label>Bed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_1__c.field-meta.xml
<CustomField>
    <fullName>Picture_1__c</fullName>
    <label>Picture 1</label>
    <type>Url</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_2__c.field-meta.xml
<CustomField>
    <fullName>Picture_2__c</fullName>
    <label>Picture 2</label>
    <type>Url</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_3__c.field-meta.xml
<CustomField>
    <fullName>Picture_3__c</fullName>
    <label>Picture 3</label>
    <type>Url</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_4__c.field-meta.xml
<CustomField>
    <fullName>Picture_4__c</fullName>
    <label>Picture 4</label>
    <type>Url</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Opportunity/fields/Picture_5__c.field-meta.xml
<CustomField>
    <fullName>Picture_5__c</fullName>
    <label>Picture 5</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Bath__c.field-meta.xml
<CustomField>
    <fullName>Bath__c</fullName>
    <label>Bath</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <label>Bed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_1__c.field-meta.xml
<CustomField>
    <fullName>Picture_1__c</fullName>
    <label>Picture 1</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_2__c.field-meta.xml
<CustomField>
    <fullName>Picture_2__c</fullName>
    <label>Picture 2</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_3__c.field-meta.xml
<CustomField>
    <fullName>Picture_3__c</fullName>
    <label>Picture 3</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_4__c.field-meta.xml
<CustomField>
    <fullName>Picture_4__c</fullName>
    <label>Picture 4</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_5__c.field-meta.xml
<CustomField>
    <fullName>Picture_5__c</fullName>
    <label>Picture 5</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price of the Property</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Owner</label>
    <referenceTo>Property_Owner__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property_Owner__c/Property_Owner__c.object-meta.xml
<CustomObject>
    <label>Property Owner</label>
    <nameField>
        <label>Sellers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/classes/triggerHelperAE.cls
public with sharing class triggerHelperAE {
    public static void createProperty(List<Opportunity> propCreate){
        List<Property__C> newProps = new List<Property__C>();
        for(Opportunity o: propCreate){
            if(o.StageName == 'Closed Won'){
                Property__C newProp = new Property__C();
                newProp.Address__c = o.Address__c;
                newProp.Bath__c = o.Bath__c;
                newProp.Bed__c = o.Bed__c;
                newProp.Location__c = o.Location__c;
                newProp.Price__c = o.Amount;
                newProp.Picture_1__c = o.Picture_1__c;
                newProp.Picture_2__c = o.Picture_2__c;
                newProp.Picture_3__c = o.Picture_3__c;
                newProp.Picture_4__c = o.Picture_4__c;
                newProp.Picture_5__c = o.Picture_5__c;
                newProp.Name = o.Name;
                newProps.add(newProp);
            }
        }
        if(newProps.size()>0){
            insert newProps;
        }
    }
    public static void createPropertyOwner(List<Opportunity> propOwnCreate){
        List<Property_Owner__c> newOwners = new List<Property_Owner__c>();
        List<User> ulist = [SELECT Name, Id, Email, Phone FROM User];
        for(Opportunity o: propOwnCreate){
            if(o.StageName == 'Closed Won'){
                for(User u: ulist){
                    if(u.Id == o.CreatedById){
                    Property_Owner__c newOwner = new Property_Owner__c();
                    newOwner.Name = u.Name;
                    newOwner.Email_Address__c = u.Email;
                    newOwner.Phone_Number__c = u.Phone;
                    newOwners.add(newOwner);
                    }
            }
            }
            

        }
        if(newOwners.size()>0){
            insert newOwners;
        }
    }
}