Fantasy Real Estate Core Package/force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/objects/Offer__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TobiDiazP2/force-app/main/default/objects/Offer__c/fields/Property_Field__c.field-meta.xml
<CustomField>
    <fullName>Property_Field__c</fullName>
    <label>Property Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TobiDiazP2/force-app/main/default/classes/OfferTriggerHelper.cls
public class OfferTriggerHelper 
{
    public static void AssignPropertyName(List<Offer__c> offers)
    {
        List<Property__c> properties = [SELECT Name, Id FROM Property__c];
        
        for(Offer__c o : offers)
        {
            for(Property__c p : properties)
            {
                if(o.Property__c == p.id)
                {
                    o.Property_Field__c = p.Name;
                }
            }
        }
    }
}