Fantasy Real Estate Core Package/force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/objects/Offer__c/fields/Offer_Amount__c.field-meta.xml
<CustomField>
    <fullName>Offer_Amount__c</fullName>
    <label>Offer Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Offer__c/fields/Potential_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Potential_Buyer__c</fullName>
    <label>Potential Buyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Offer__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TobiDiazP2/force-app/main/default/objects/Offer__c/fields/Property_Field__c.field-meta.xml
<CustomField>
    <fullName>Property_Field__c</fullName>
    <label>Property Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TobiDiazP2/force-app/main/default/objects/Property__c/fields/Bidding_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bidding_Stage__c</fullName>
    <label>Bidding Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TobiDiazP2/force-app/main/default/classes/TDApexTest.cls
@isTest
public class TDApexTest 
{
	@isTest
    private static void AssignPropertyNameSingleTest()
    {
        List<Property__c> properties = new List<Property__c>();
        List<Offer__c> offers = new List<Offer__c>();
        List<Contact> potentialBuyers = new List<Contact>();
        
        Contact c = new Contact();
        c.LastName = 'Johnson';
        
        potentialBuyers.add(c);
        
        insert potentialBuyers;
        
        List<Contact> contactIds = [SELECT Id FROM Contact];
        
        integer i;
        
        for(i = 0; i < 1; i++)
        {
            Property__c prop = new Property__c();
            prop.Name = 'My House';
            prop.Bidding_Stage__c = 'Open';
            properties.add(prop);
        }
        
        insert properties;
        
        List<Property__c> propIds = [SELECT Id FROM Property__c];
        
        for(i = 0; i < 1; i++)
        {
            Offer__c offer = new Offer__c();
            offer.Name = 'New Offer';
        	offer.Offer_Amount__c = 9000;
        	offer.Potential_Buyer__c = contactIds[0].Id;
        	offer.Property__c = propIds[i].Id;
            offers.add(offer);
        }
        
        database.insert(offers);
        
        OfferTriggerHelper.AssignPropertyName(offers);
        
        for(i = 0; i < 1; i++)
        {
            System.assertEquals('My House', offers[i].Property_Field__c);
        }
    }
    
    @isTest
    private static void AssignPropertyNameBulkTest()
    {
        List<Property__c> properties = new List<Property__c>();
        List<Offer__c> offers = new List<Offer__c>();
        List<Contact> potentialBuyers = new List<Contact>();
        
        Contact c = new Contact();
        c.LastName = 'Johnson';
        
        potentialBuyers.add(c);
        
        insert potentialBuyers;
        
        List<Contact> contactIds = [SELECT Id FROM Contact];
        
        integer i;
        
        for(i = 0; i < 100; i++)
        {
            Property__c prop = new Property__c();
            prop.Name = 'My House';
            prop.Bidding_Stage__c = 'Open';
            properties.add(prop);
        }
        
        insert properties;
        
        List<Property__c> propIds = [SELECT Id FROM Property__c];
        
        for(i = 0; i < 100; i++)
        {
            Offer__c offer = new Offer__c();
            offer.Name = 'New Offer';
        	offer.Offer_Amount__c = 9000;
        	offer.Potential_Buyer__c = contactIds[0].Id;
        	offer.Property__c = propIds[i].Id;
            offers.add(offer);
        }
        
        database.insert(offers);
        
        OfferTriggerHelper.AssignPropertyName(offers);
        
        for(i = 0; i < 100; i++)
        {
            System.assertEquals('My House', offers[i].Property_Field__c);
        }
    }
    
    @isTest
    private static void getPropertiesSingleTest()
    {
        List<Property__c> properties = new List<Property__c>();
        
        for(integer i = 0; i < 1; i++)
        {
            Property__c prop = new Property__c();
            prop.Name = 'My House';
            prop.Bidding_Stage__c = 'Open';
            properties.add(prop);
        }
        
        insert properties;
        
        List<Property__c> controllerProperties = PropertyController.getProperties();
        
        System.assertEquals(controllerProperties.size(), properties.size());
    }
    
    @isTest
    private static void getPropertiesBulkTest()
    {
        
    }
    
    @isTest
    private static void OfferHelperSingleTest()
    {
        List<Property__c> properties = new List<Property__c>();
        List<Offer__c> offers = new List<Offer__c>();
        List<Contact> potentialBuyers = new List<Contact>();
        
        Contact c = new Contact();
        c.LastName = 'Johnson';
        
        potentialBuyers.add(c);
        
        insert potentialBuyers;
        
        List<Contact> contactIds = [SELECT Id FROM Contact];
        
        integer i;
        
        for(i = 0; i < 1; i++)
        {
            Property__c prop = new Property__c();
            prop.Name = 'My House';
            prop.Bidding_Stage__c = 'Open';
            properties.add(prop);
        }
        
        insert properties;
        
        List<Property__c> propIds = [SELECT Id FROM Property__c];
        
        for(i = 0; i < 1; i++)
        {
            Offer__c offer = new Offer__c();
            offer.Name = 'New Offer';
        	offer.Offer_Amount__c = 9000;
        	offer.Potential_Buyer__c = contactIds[0].Id;
        	offer.Property__c = propIds[i].Id;
            offers.add(offer);
        }
        
        database.insert(offers);
        
        List<Offer__c> newOffers = OfferApexHelper.OfferHelper();
        
        System.assertEquals(offers.size(), newOffers.size());
    }
    
    @isTest
    private static void OfferHelperBulkTest()
    {
        List<Property__c> properties = new List<Property__c>();
        List<Offer__c> offers = new List<Offer__c>();
        List<Contact> potentialBuyers = new List<Contact>();
        
        Contact c = new Contact();
        c.LastName = 'Johnson';
        
        potentialBuyers.add(c);
        
        insert potentialBuyers;
        
        List<Contact> contactIds = [SELECT Id FROM Contact];
        
        integer i;
        
        for(i = 0; i < 100; i++)
        {
            Property__c prop = new Property__c();
            prop.Name = 'My House';
            prop.Bidding_Stage__c = 'Open';
            properties.add(prop);
        }
        
        insert properties;
        
        List<Property__c> propIds = [SELECT Id FROM Property__c];
        
        for(i = 0; i < 100; i++)
        {
            Offer__c offer = new Offer__c();
            offer.Name = 'New Offer';
        	offer.Offer_Amount__c = 9000;
        	offer.Potential_Buyer__c = contactIds[0].Id;
        	offer.Property__c = propIds[i].Id;
            offers.add(offer);
        }
        
        database.insert(offers);
        
        List<Offer__c> newOffers = OfferApexHelper.OfferHelper();
        
        System.assertEquals(offers.size(), newOffers.size());
    }
}