Fantasy Real Estate Core Package/force-app/main/default/objects/Archive_Property__c/Archive_Property__c.object-meta.xml
<CustomObject>
    <label>Archive-Property</label>
    <nameField>
        <label>Archive-Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archive-Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fantasy Real Estate Core Package/force-app/main/default/objects/Archive_Property__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <label>Bed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Archive_Property__c/fields/Bidding_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bidding_Stage__c</fullName>
    <label>Bidding Stage</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Archive_Property__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <label>Property Owner</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Archive_Property__c/fields/Realtor__c.field-meta.xml
<CustomField>
    <fullName>Realtor__c</fullName>
    <label>Realtor</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FantasyRealEstateND_Package/Dragon-Sales-Force-Project 2/force-app/main/default/objects/Property__c/fields/Accepted_Bid__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Bid__c</fullName>
    <label>Accepted Bid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Property__c/fields/Bath__c.field-meta.xml
<CustomField>
    <fullName>Bath__c</fullName>
    <label>Bath</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <label>Bed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TobiDiazP2/force-app/main/default/objects/Property__c/fields/Bidding_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bidding_Stage__c</fullName>
    <label>Bidding Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price of the Property</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Property__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Owner</label>
    <referenceTo>Property_Owner__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Realtor__c.field-meta.xml
<CustomField>
    <fullName>Realtor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realtor</label>
    <referenceTo>Realtor__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Property_Owner__c/Property_Owner__c.object-meta.xml
<CustomObject>
    <label>Property Owner</label>
    <nameField>
        <label>Sellers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Fantasy Real Estate Core Package/force-app/main/default/objects/Realtor__c/Realtor__c.object-meta.xml
<CustomObject>
    <label>Realtor</label>
    <nameField>
        <label>Realtor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realtors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FantasyRealEstateND_Package/Dragon-Sales-Force-Project 2/force-app/main/default/classes/PropertyTriggerHelper.cls
public class PropertyTriggerHelper {
    
    //Assigns the description value of property before update
    public static void UpdateDescription(List<Property__c> prop){
        //iterates through prop (trigger.new) and populates the description field based on other field values
        for(Property__c propIt: prop){
            propIt.Description__c = propIt.Location__c + ' location, \n' + propIt.Bed__c + ' beds ' + propIt.Bath__c + ' baths. \n' + 'Asking Price: ' + propIt.Price__c;
        }       
    }
    
    //Creates an Archive Property record of a property that is being updated to Closed Sold/Unsold
    //Archive Property has the same values of the property
    public static void ArchiveProperty(List<Property__c> prop){
        List<Archive_Property__c> archiveProp = new List<Archive_Property__c>();
        for(Property__c propIt: prop){
            if(propIt.Bidding_Stage__c == 'Closed Sold' || propIt.Bidding_Stage__c == 'Closed Unsold'){
                Archive_Property__c newArchive = new Archive_property__c();
                newArchive.Accepted_Bid__c = propIt.Accepted_Bid__c;
                newArchive.Address__c = propIt.Address__c;
                newArchive.Bath__c = propIt.Bath__c;
                newArchive.Bed__c = propIt.Bed__c;
                newArchive.Bidding_Stage__c = propIt.Bidding_Stage__c;
                newArchive.Name = propIt.Name;
                newArchive.Price__c = propIt.Price__c;
                newArchive.Property_Owner__c = propIt.Property_Owner__c;
                newArchive.Realtor__c = propIt.Realtor__c;
                newArchive.Location__c = propIt.Location__c;
                archiveProp.add(newArchive);
            }
  		}
        database.insert(archiveProp);
    }
    
    //Deletes properties after property is updated to be Closed Sold/Unsold
    public static void DeleteArchivedProperty(){
        List<Property__c> deleteProp = [SELECT id FROM Property__c WHERE Bidding_Stage__c LIKE 'Closed%'];
        
        database.delete(deleteProp);
    }
}