Fantasy Real Estate Core Package/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Fantasy Real Estate Core Package/force-app/main/default/objects/Property__c/fields/Bath__c.field-meta.xml
<CustomField>
    <fullName>Bath__c</fullName>
    <label>Bath</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <label>Bed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_1__c.field-meta.xml
<CustomField>
    <fullName>Picture_1__c</fullName>
    <label>Picture 1</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_2__c.field-meta.xml
<CustomField>
    <fullName>Picture_2__c</fullName>
    <label>Picture 2</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_3__c.field-meta.xml
<CustomField>
    <fullName>Picture_3__c</fullName>
    <label>Picture 3</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_4__c.field-meta.xml
<CustomField>
    <fullName>Picture_4__c</fullName>
    <label>Picture 4</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_5__c.field-meta.xml
<CustomField>
    <fullName>Picture_5__c</fullName>
    <label>Picture 5</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price of the Property</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

FantasyRealEstateND_Package/Dragon-Sales-Force-Project 2/force-app/main/default/classes/PicklistViewerGetFields.cls
public with sharing class PicklistViewerGetFields {
    @AuraEnabled(cacheable = true)
    public static List<Property__c> getPropertyFields(){
        //returns properties to be used in the Picklist Viewer LWC/Aura
        return[SELECT Name, Address__c, Location__c, Bed__c, Bath__c, Price__c, Picture_1__c, Picture_2__c, Picture_3__c, Picture_4__c, Picture_5__c
              FROM Property__c];    
    }
    
}