DragonSalesForceProject2/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Bath__c.field-meta.xml
<CustomField>
    <fullName>Bath__c</fullName>
    <label>Bath</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Bed__c.field-meta.xml
<CustomField>
    <fullName>Bed__c</fullName>
    <label>Bed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/combo_desc__c.field-meta.xml
<CustomField>
    <fullName>combo_desc__c</fullName>
    <label>combo desc</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_1__c.field-meta.xml
<CustomField>
    <fullName>Picture_1__c</fullName>
    <label>Picture 1</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_2__c.field-meta.xml
<CustomField>
    <fullName>Picture_2__c</fullName>
    <label>Picture 2</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_3__c.field-meta.xml
<CustomField>
    <fullName>Picture_3__c</fullName>
    <label>Picture 3</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_4__c.field-meta.xml
<CustomField>
    <fullName>Picture_4__c</fullName>
    <label>Picture 4</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Picture_5__c.field-meta.xml
<CustomField>
    <fullName>Picture_5__c</fullName>
    <label>Picture 5</label>
    <type>Url</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price of the Property</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Owner</label>
    <referenceTo>Property_Owner__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property__c/fields/Realtor__c.field-meta.xml
<CustomField>
    <fullName>Realtor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realtor</label>
    <referenceTo>Realtor__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

DragonSalesForceProject2/force-app/main/default/objects/Property_Owner__c/Property_Owner__c.object-meta.xml
<CustomObject>
    <label>Property Owner</label>
    <nameField>
        <label>Sellers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/objects/Realtor__c/Realtor__c.object-meta.xml
<CustomObject>
    <label>Realtor</label>
    <nameField>
        <label>Realtor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realtors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DragonSalesForceProject2/force-app/main/default/classes/propertyAppHelper.cls
public with sharing class propertyAppHelper {
    @AuraEnabled(cacheable=true)
    public static List<Property__C> getPropertyInfo(){
        List<Property__C> pList = [SELECT Id, Name, Address__c, Bath__c, Bed__c, Description__c, Location__c, Picture_1__c, Picture_2__c, Picture_4__c, Picture_3__c, Picture_5__c, Price__c, Property_Owner__c, Realtor__c,combo_desc__C FROM Property__c];
        return pList;

    }
    @AuraEnabled
    public static List<Property__C> getAllRegions(){
        List<Property__C> rList = [SELECT Location__c FROM Property__C];
        return rList;
    }
}